name = "the-prism-lab"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
output_directory = "out"

[build.environment]
NODE_VERSION = "18"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
